CREATE TABLE IF NOT EXISTS songify."songs" (
    "id" INT,
    "title" TEXT,
    "artist" TEXT,
    "year" TEXT
);
INSERT INTO songify."songs" VALUES
    (0,'Ballroom Blitz','Sweet','1973'),
    (1,'Karn Evil 9','Emerson, Lake & Palmer','1973'),
    (2,'Hello It''s Me','Todd Rundgren','1972'),
    (3,'Jane','Jefferson Starship','1979'),
    (4,'Fly To The Angels','Slaughter','1990'),
    (5,'Them Bones','Alice In Chains','1992'),
    (6,'The First Cut Is The Deepest','Rod Stewart','1976'),
    (7,'Honky Tonk Women','Rolling Stones','1969'),
    (8,'What About Love?','Heart',NULL),
    (9,'The Changeling','The Doors','1971'),
    (10,'Starship Trooper','Yes','1971'),
    (11,'Life''s Been Good','Joe Walsh',NULL),
    (12,'Don''t Stop','Fleetwood Mac','1977'),
    (13,'All Apologies','Nirvana','1993'),
    (14,'Far Behind','Candlebox','1993'),
    (15,'Key To The Rhyme','Lake',NULL),
    (16,'Let ''Em In','Paul McCartney & Wings',NULL),
    (17,'Fortune Teller','Rolling Stones',NULL),
    (18,'Captain Jack','Billy Joel','1973'),
    (19,'Pretending','Eric Clapton','1989'),
    (20,'Roadhouse Blues','The Doors','1967'),
    (21,'I Remember You','Skid Row','1989'),
    (22,'Reprise / Day in the Life','The Beatles','1967'),
    (23,'Have You Ever Seen the Rain?','Creedence Clearwater Revival','1971'),
    (24,'All She Wants to Do Is Dance','Don Henley','1985'),
    (25,'Riders On The Storm','The Doors','1971'),
    (26,'Me and Bobby McGee','Grateful Dead',NULL),
    (27,'Thunder Road','Bruce Springsteen','1975'),
    (28,'ANOTHER TRICKY DAY','The Who',NULL),
    (29,'China Girl','David Bowie','1983'),
    (30,'Train, Train','Blackfoot','1979'),
    (31,'Your Cash Ain''t Nothin But Trash','Steve Miller Band',NULL),
    (32,'Carry On','Crosby, Stills, Nash & Young','1970'),
    (33,'December','Collective Soul',NULL),
    (34,'Smells Like Teen Spirit','Nirvana','1991'),
    (35,'Diamonds And Rust','Judas Priest',NULL),
    (36,'Today','Smashing Pumpkins','1993'),
    (37,'The Spirit of Radio','Rush','1980'),
    (38,'BAD BOY','The Beatles','1965'),
    (39,'I Want To Hold Your Hand','The Beatles','1963'),
    (40,'COVER OF THE ROLLING STONE','Dr. Hook & the Medicine Show',NULL),
    (41,'Illegal Smile','John Prine',NULL),
    (42,'Right Now','Van Halen','1991'),
    (43,'Monday Morning','Fleetwood Mac','1975'),
    (44,'Lazy','Deep Purple','1972'),
    (45,'Another Brick In The Wall','Pink Floyd','1979'),
    (46,'WAR','Edwin Starr','1970'),
    (47,'Spirits In The Material World','The Police','1981'),
    (48,'Funk #49','Joe Walsh','2012'),
    (49,'Gypsy Road','Cinderella','1988'),
    (50,'Woman','Legs Diamond',NULL),
    (51,'Ain''t Too Proud to Beg','Rolling Stones','1974'),
    (52,'The Grand Illusion','Styx','1977'),
    (53,'Bullfrog Blues','Rory Gallagher','SONGFACTS.COM'),
    (54,'#9 Dream','John Lennon','1974'),
    (55,'Mystery Achievement','The Pretenders',NULL),
    (56,'Cowboy','Kid Rock','1998'),
    (57,'Listen To What The Man Says','Paul McCartney & Wings',NULL),
    (58,'Love Reign O''er Me','The Who','1973'),
    (59,'All Night Long','Joe Walsh','1980'),
    (60,'Hot Rod Lincoln','Commander Cody','1971'),
    (61,'Twilight Zone','Golden Earring','1983'),
    (62,'Goodbye Stranger','Supertramp','1979'),
    (63,'Drive My Car','The Beatles','1965'),
    (64,'Panic in Detroit','David Bowie',NULL),
    (65,'Yankee Rose','David Lee Roth','1986'),
    (66,'AIN''T NO SUNSHINE','Bill Withers','1971'),
    (67,'Keep Pushin'' 1977','REO Speedwagon',NULL),
    (68,'Cry Sister','Royal Bliss',NULL),
    (69,'Don''t Bring Me Down','Animals II','1966'),
    (70,'Sweet Leaf','Black Sabbath','1971'),
    (71,'Fooling Yourself','Styx','1977'),
    (72,'Jackie Blue','Ozark Mountain Daredevils','1975'),
    (73,'You Shook Me All Night Long','AC/DC','1980'),
    (74,'Born On the Bayou','Creedence Clearwater Revival','1969'),
    (75,'Woman From Tokyo','Deep Purple',NULL),
    (76,'San Franciscan Nights','The Animals','1967'),
    (77,'Finding My Way','Rush',NULL),
    (78,'Come Together','Aerosmith',NULL),
    (79,'Empty Spaces','Pink Floyd','1979'),
    (80,'A Day In The Life','The Beatles','1967'),
    (81,'She''s So Cold','Rolling Stones',NULL),
    (82,'Tempted','Squeeze','1981'),
    (83,'Careful With That Axe, Eugene','Pink Floyd','1969'),
    (84,'What''s Your Name','Lynyrd Skynyrd','1977'),
    (85,'Comedown','Bush','1994'),
    (86,'Norwegian Wood','The Beatles','1965'),
    (87,'Small Town','John Mellencamp','1985'),
    (88,'Inside Out','Eve 6',NULL),
    (89,'Girls, Girls, Girls','Motley Crue','1987'),
    (90,'What You Need','INXS','1985'),
    (91,'Alone Again','Dokken',NULL),
    (92,'THE BITCH IS BACK','Elton John','1974'),
    (93,'Do You Remember Rock ''n'' Roll Radio','The Ramones','1980'),
    (94,'U.S. Blues','Grateful Dead',NULL),
    (95,'Baby Hold On','Eddie Money','1977'),
    (96,'Love Her Madly','The Doors','1971'),
    (97,'Summertime Blues','Rush',NULL),
    (98,'Somebody','Bryan Adams','1984'),
    (99,'Suite: Judy Blue Eyes','Crosby, Stills & Nash','1969');
