CREATE TABLE IF NOT EXISTS vr_startup."employees" (
    "employee_id" INT,
    "first_name" TEXT,
    "last_name" TEXT,
    "location" TEXT,
    "position" TEXT,
    "personality" TEXT,
    "current_project" INT
);
INSERT INTO vr_startup."employees" VALUES
    (1,'Shannan','Arlow','MO','Designer','ISTJ',2),
    (2,'Philippe','Fownes','NY','Designer','ENFJ',2),
    (3,'Ambrosi','Dawkes','TX','Designer','ISTP',NULL),
    (4,'Mordy','Mosdall','FL','Developer','ISTP',NULL),
    (5,'Kalie','Yearsley','IL','Developer','ESTJ',2),
    (6,'Winona','Goodanew','MI','Lead','INFJ',NULL),
    (7,'Esma','Kidstone','NC','DBA','ESFP',NULL),
    (8,'Delmore','Ruperti','ID','DBA','ENFJ',NULL),
    (9,'Ora','Singers','NY','Designer','ISTP',NULL),
    (10,'Daphna','Murty','VA','Designer','ESFJ',NULL),
    (11,'Anselm','Rossin','FL','Lead','ISFP',NULL),
    (12,'Hannis','Galea','MA','Lead','ESTJ',3),
    (13,'Edi','Vinau','TX','DBA','INTP',NULL),
    (14,'Mirella','Parram','NJ','Project Manager','ISTJ',6),
    (15,'Mitchel','Guinness','TN','Project Manager','ENTP',NULL),
    (16,'Delphinia','Ferrant','NY','Project Manager','ENFP',5),
    (17,'Ingeborg','Prickett','MN','Project Manager','ENFJ',4),
    (18,'Chrissie','Gricks','FL','Designer','ISTP',NULL),
    (19,'Enrico','Corden','MD','Lead','ISTP',NULL),
    (20,'Tremaine','Reyner','NY','Developer','ENFP',NULL),
    (21,'Elva','Golby','IL','Project Manager','ENTJ',NULL),
    (22,'Worden','Zorro','FL','DBA','ISFP',NULL),
    (23,'Sigismondo','Wimbury','CT','Developer','INTP',NULL),
    (24,'Moina','Astall','NV','DBA','ENFJ',1),
    (25,'Lucine','Leighfield','MA','DBA','ESTJ',NULL),
    (26,'Lezley','Lemarie','FL','Designer','INFP',NULL),
    (27,'Lacy','Escritt','OK','Developer','ISTJ',7),
    (28,'Elwin','Prandy','MO','Project Manager','ENTP',NULL),
    (29,'Adda','Savege','CA','Lead','ENFJ',NULL),
    (30,'Sisile','Fleay','WA','Designer','ESFJ',NULL),
    (31,'Joscelin','Blaszkiewicz','IL','Developer','ISFJ',7),
    (32,'Wally','Derr','FL','DBA','ISFJ',NULL),
    (33,'Ludovika','Elby','ND','Lead','ESTJ',NULL),
    (34,'Andy','Banasevich','MN','DBA','ENFJ',NULL),
    (35,'Hale','Dyott','TX','DBA','ISFP',7),
    (36,'Christi','Muge','MO','Developer','ENFJ',NULL),
    (37,'Sydelle','Hartell','NY','Designer','ISFP',NULL),
    (38,'Rey','Branca','TX','Project Manager','ESFJ',NULL),
    (39,'Edgard','Wilhelmy','GA','Lead','ENTP',NULL),
    (40,'Larine','Talman','GA','Lead','INFJ',7),
    (41,'Mahalia','McCall','MN','Developer','INFJ',NULL),
    (42,'Trey','Garcia','TX','Lead','INTJ',NULL),
    (43,'Dew','Steffan','NC','Lead','ENTP',NULL),
    (44,'Dorisa','Cherrie','PA','Project Manager','ENTJ',5),
    (45,'Berenice','Waycott','NC','Developer','INFJ',NULL),
    (46,'Harriet','Girardini','IA','Project Manager','INFP',NULL),
    (47,'Wendell','Jest','TX','Project Manager','ISFP',NULL),
    (48,'Antons','Bartelli','IN','Designer','ESFP',7),
    (49,'Dode','McGruar','GA','DBA','INTP',NULL),
    (50,'Nanete','Lyes','NE','Project Manager','ESFJ',NULL);
